export const FETCH_PROJECT_REQUEST = "FETCH_PROJECT_REQUEST";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILURE = "FETCH_PROJECT_FAILUER";

export const FETCH_PROJECT_BY_ID_REQUEST = "FETCH_PROJECT_BY_ID_REQUEST";
export const FETCH_PROJECT_BY_ID_SUCCESS = "FETCH_PROJECT_BY_ID_SUCCESS";
export const FETCH_PROJECT_BY_ID_FAILURE = "FETCH_PROJECT_BY_ID_FAILUER";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILUER";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAILURE = "FETCH_PROJECT_FAILUER";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILUER";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESS = "INVITE_TO_PROJECT_SUCCESS";
export const INVITE_TO_PROJECT_FAILURE = "DELETE_PROJECT_FAILUER";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILURE = "ACCEPT_INVITATION_FAILUER";
